#include <stdlib.h>
#include <time.h>
#include <stdio.h>

/**
 * main - Checks whether a random number n, generated by the rand function
 * is  negative, positive or zero and prints the result to the console
 *
 * Return: 0 (success)
 */
int main(void)
{
	int n;

	srand(time(0))
	n = rand() - RAND_MAX / 2;
	if (n > 0)
	{
		printf("%d is positive\n", n);
	}
	else if (n < 0)
	{
		printf("%d is negative\n", n);
	}
	else
	{
		printf("%d is zero\n", n);
	}
	return (0);
}
